const express = require('express')
const cors = require('cors')
const app = express()
const port = process.env.PORT || 5000
const patientsRouter = require('./routes/patients')
const trialsRouter = require('./routes/trials')
app.use(cors())
app.use(express.urlencoded({ extended: false }))
app.use(express.json())
app.use('/patients', patientsRouter)
app.use('/trials', trialsRouter)
app.listen(port, () => console.log(`Listening on port ${port}`))
